### ISSUE TITLE
pdf schematics seem to be broken 

### ISSUE THREAD

**Issue by jmio23** [homebrew8088/8088-PC-Compatible#2]
I've tried acrobat, word, chrome and a whole bunch of others, always looks like this

![Screenshot_20230616-153318](https://github.com/homebrew8088/8088-PC-Compatible/assets/26100869/eca08d73-f117-42e8-bb24-0878f1e3c2b2)

**Comment by cuvtixo** [comment]
er, jmio23, firstly, there's 8 different schematics, I think you are looking at the 8088.pdf . But, THAT IS THE SCHEMATIC.  There's nothing more to these. They are not full electronic diagrams with symbols for resistors, capacitors, etc. It is mainly just the integrated circuits, and for example, 4 Slot Main Board.pdf has the various numerical values, but what you see is what you get.  I'm sorry you were expecting more.

**Comment by homebrew8088** [comment]
That is how I draw my schematics. When I add the net lines it gets to busy for me to look at. I just know the chips by memory at this point and assign the pins where they need to go. 

Yes they are bit out of date. I should get some newer ones published. **But** when you open the Kicad project files you will get the most up to date schematic that I been working on. Plus if you open the PCB files you can highlight the traces and see how everything is connected.

**Comment by jmio23** [comment]
> That is how I draw my schematics. When I add the net lines it gets to busy for me to look at. I just know the chips by memory at this point and assign the pins where they need to go.
> 
> Yes they are bit out of date. I should get some newer ones published. **But** when you open the Kicad project files you will get the most up to date schematic that I been working on. Plus if you open the PCB files you can highlight the traces and see how everything is connected.

thanks I'll check those files out; I've never used kiCad, will I be able to see for eg the entire circuit for the ISA pinout and ISA/BIOS connections? Unfortunately due to disability, even installing kiCad, let alone using it, will be a challenge for me, but if it will give me those details then it's worth the pain

I am trying to learn enough, so that I can add a solution for low rez monochrome graphics to my v20-mbc; an ISA bus i can plug a video (or whatever) card into is my preferred option; I was contemplating an ISA emulation over SPI, or an emulation of both the bus and graphics over SPI, but that feels a convoluted approach (esp considering what I still need to learn) if I can persuade the atmega32/BIOS to handle a hardware ISA bus
